import { createRequire } from 'node:module'
import assert from 'node:assert/strict'
import { readFile, writeFile } from 'node:fs/promises'
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '/tmp/amx-browser/node_modules/playwright')
const browser = await chromium.launch({ headless:true })
const page = await browser.newPage({ acceptDownloads:true })
const errors=[]
page.on('pageerror',e=>errors.push(e.message))
const results=[]
const click = name => page.getByRole('button',{name,exact:true}).click()
const nav = name => click(name)
const check = text => page.getByRole('checkbox',{name:text}).check()
const notice = async text => assert.ok((await page.getByRole('status').innerText()).includes(text))
const role = value => page.getByLabel('Simulated role:').selectOption(value)
const start = async()=>{await page.goto('http://localhost:5173'); await click('View case SYN-007-001')}
const verify = async()=>{await check('I, the human CSR, attest'); await click('Record CSR attestation')}
const assess = async()=>{await nav('AI-Assisted Assessment'); await check('I have reviewed'); await click('Record manual assessment'); await click('Request Supervisor review')}
const approve = async()=>{await nav('Supervisor Authorization'); await role('Supervisor'); await check('I, the human Supervisor'); await click('Authorize simulated $500 reversal'); await role('CSR')}
const prepare = async()=>{await start(); await verify(); await assess(); await approve(); await nav('Action & Closure')}
const test=async(name,fn)=>{try{await fn(); await nav('Audit History'); const pending=page.waitForEvent('download'); await click('Download JSON audit'); await (await pending).saveAs(`docs/test-artifacts/scenario-${results.length+1}-audit.json`); results.push({name,result:'PASS'}); console.log(`PASS ${name}`)}catch(e){results.push({name,result:'FAIL',error:e.message}); console.log(`FAIL ${name}: ${e.message}`)}}
try {
await test('Verification bypasses and unauthorized human actions',async()=>{await start(); await click('Record CSR attestation'); await notice('explicitly attest'); await role('Supervisor'); await check('I, the human CSR, attest'); await click('Record CSR attestation'); await notice('restricted'); await role('CSR'); await nav('AI-Assisted Assessment'); for(const name of ['Run simulated AI','Record human AI review','Record manual assessment']){await click(name);await notice('verification is mandatory')} await nav('Action & Closure'); await click('Perform simulated $500 reversal'); await notice('Supervisor assistance is needed for this action. No approval or account change has been performed.')})
await test('Missing evidence and changed context invalidate approval',async()=>{await prepare(); await nav('Identity Verification'); await page.getByLabel('Required synthetic identity').uncheck(); await click('Save case information'); await notice('must be completed again'); await verify(); await notice('evidence is unavailable'); await page.getByLabel('Required synthetic identity').check(); await page.getByLabel('Case context').selectOption('Fictional duplicate-charge context added'); await click('Save case information'); await nav('Action & Closure'); await click('Perform simulated $500 reversal'); await notice('Supervisor assistance is needed')})
await test('AI usable and uncertain output requires explicit human review',async()=>{await start(); await verify(); await nav('AI-Assisted Assessment'); await click('Run simulated AI'); assert.ok(await page.getByRole('heading',{name:'Simulated AI · usable'}).isVisible()); await click('Record human AI review'); await notice('Explicit human review'); await page.getByLabel('Simulated AI response').selectOption('uncertain'); await click('Run simulated AI'); assert.ok(await page.getByRole('alert').isVisible()); await check('I have reviewed'); await click('Record human AI review'); await notice('Acknowledge the uncertainty'); await check('I acknowledge the uncertain'); await click('Record human AI review'); await notice('Human assessment recorded')})
await test('AI unusable and system failure support guarded manual fallback',async()=>{for(const mode of ['unusable','failed']){await start();await verify();await nav('AI-Assisted Assessment');await page.getByLabel('Simulated AI response').selectOption(mode);await click('Run simulated AI');await notice('Use manual fallback');await check('I have reviewed');await click('Record human AI review');await notice('Use manual fallback');await click('Record manual assessment');await notice('Human assessment recorded')}})
await test('Supervisor approval is separate; role and explicit decision guards',async()=>{await start();await verify();await assess();await nav('Supervisor Authorization');await check('I, the human Supervisor');await click('Authorize simulated $500 reversal');await notice('restricted');await role('Supervisor');await page.getByRole('checkbox',{name:'I, the human Supervisor'}).uncheck();await click('Authorize simulated $500 reversal');await notice('explicitly confirm');await check('I, the human Supervisor');await click('Authorize simulated $500 reversal');await notice('separate CSR-triggered');await nav('Action & Closure');await click('Perform simulated $500 reversal');await notice('restricted');await click('Confirm simulated closure');await notice('restricted')})
await test('Failed mock reversal stays open; duplicate and closure controls disabled',async()=>{await prepare();await page.getByLabel('Simulated reversal outcome').selectOption('failed');await click('Perform simulated $500 reversal');await notice('failed. Case remains open');assert.ok(await page.getByRole('button',{name:'Perform simulated $500 reversal',exact:true}).isDisabled());assert.ok(await page.getByRole('button',{name:'Confirm simulated closure',exact:true}).isDisabled())})
await test('Rejected and withdrawn cases stay unresolved',async()=>{await start();await verify();await assess();await nav('Supervisor Authorization');await role('Supervisor');await check('I, the human Supervisor');await click('Reject request');await notice('Case remains open for review');await nav('Action & Closure');assert.ok(await page.getByRole('button',{name:'Confirm simulated closure',exact:true}).isDisabled());await start();await role('CSR');await verify();await assess();await nav('Action & Closure');await check('I, the human CSR, explicitly');await click('Withdraw reversal request');await notice('Case remains open for review');assert.ok(await page.getByRole('button',{name:'Confirm simulated closure',exact:true}).isDisabled())})
await test('Complete $500 success, separate human closure, audit JSON and export immutability',async()=>{await start();await verify();await nav('AI-Assisted Assessment');await click('Run simulated AI');await check('I have reviewed');await click('Record human AI review');await click('Request Supervisor review');await approve();await nav('Action & Closure');await click('Confirm simulated closure');await notice('successfully resolved');await click('Perform simulated $500 reversal');await notice('Case is still open');assert.ok(await page.getByRole('button',{name:'Perform simulated $500 reversal',exact:true}).isDisabled());await click('Confirm simulated closure');await notice('Explicit human CSR confirmation');await check('I, the human CSR, explicitly');await click('Confirm simulated closure');await notice('confirmed simulated case closure');await nav('Audit History');const before=await page.locator('.audit-list').innerText();const downloadPromise=page.waitForEvent('download');await click('Download JSON audit');const download=await downloadPromise;await download.saveAs('docs/test-artifacts/success-audit.json');const data=JSON.parse(await readFile('docs/test-artifacts/success-audit.json','utf8'));assert.equal(data.simulationOnly,true);assert.equal(data.cases.length,3);assert.equal(data.cases[0].status,'Closed · Simulated');for(const t of ['verification_attestation','simulated_ai_output','human_assessment','supervisor_approval','csr_mock_reversal_triggered','simulated_action_result','human_closure_confirmation','case_transition'])assert.ok(data.cases[0].events.some(e=>e.type===t));assert.equal(await page.locator('.audit-list').innerText(),before);await page.screenshot({path:'docs/test-artifacts/success-audit.png',fullPage:true})})
await test('Browser refresh resets all cases and audit',async()=>{await page.reload();await page.getByRole('button',{name:'View case SYN-007-001'}).waitFor();assert.equal(await page.getByText('Open · Unverified',{exact:true}).count(),3);await click('View case SYN-007-001');await nav('Audit History');assert.ok(await page.getByText('No workflow events recorded for this case.').isVisible());assert.deepEqual(errors,[])})
} finally {await writeFile('docs/test-artifacts/browser-results.json',JSON.stringify({browser:browser.version(),results,pageErrors:errors},null,2));await browser.close()}
if(results.some(r=>r.result==='FAIL'))process.exitCode=1
