import { createRequire } from 'node:module'
import { openMaterialFixture, assertEvidenceSectionAbsent, withAIOutcome, withReversalOutcome, openRoutingFixture } from './browser-fixtures.mjs'
import assert from 'node:assert/strict'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '/tmp/amx-browser/node_modules/playwright')
const artifactDir = process.env.TEST_ARTIFACT_DIR || 'docs/test-artifacts'
await mkdir(artifactDir, { recursive: true })
const browser = await chromium.launch({ headless:true })
const page = await browser.newPage({ acceptDownloads:true })
const errors=[]
page.on('pageerror',e=>errors.push(e.message))
const results=[]
const click = name => page.getByRole('button',{name,exact:true}).click()
const nav = name => click(name)
const check = text => page.getByRole('checkbox',{name:text}).check()
const notice = async text => assert.ok((await page.getByRole('status').innerText()).includes(text))
const role = value => page.getByLabel('Role:').selectOption(value)
const start = async()=>{await page.goto('http://localhost:5173'); await click('View case SYN-007-001')}
const verify = async()=>{await check('I, the CSR, confirm that'); await click('Confirm Verification')}
const assess = async()=>{await nav('AI Assessment'); await click('Run AI Assessment');await check('I have reviewed');await click('Record human AI review'); await click('Request Supervisor review')}
const approve = async()=>{await nav('Supervisor Review'); await role('Supervisor'); await check('I, the human Supervisor'); await click('Approve Reversal'); await role('CSR')}
const prepare = async()=>{await start(); await verify(); await assess(); await approve(); await nav('Action & Closure')}
const test=async(name,fn)=>{try{await fn(); await nav('Audit History'); const pending=page.waitForEvent('download'); await click('Download JSON audit'); await (await pending).saveAs(`${artifactDir}/scenario-${results.length+1}-audit.json`); results.push({name,result:'PASS'}); console.log(`PASS ${name}`)}catch(e){results.push({name,result:'FAIL',error:e.message}); console.log(`FAIL ${name}: ${e.message}`)}}
try {
await test('Professional language across all screens with visible disclosure and unchanged stored records',async()=>{
 await page.goto('http://localhost:5173')
 const disclosure='Training environment · No live account access'
 const inspect=async()=>{assert.equal(await page.locator('.simulation-banner').innerText(),disclosure);const content=(await page.locator('body').innerText()).replace(disclosure,'');assert.ok(!/\b(project-specific|simulated|fictional|synthetic|fake|demo|demonstration|simulation|prototype|classroom|mock)\b/i.test(content),content)}
 await inspect();assert.ok((await page.locator('.customer').first().innerText()).includes('Natalie Mercer'));await click('Create New Case');await inspect();assert.equal(await page.getByLabel('Customer name').locator('option').nth(1).innerText(),'Adrian Westbrook');await click('Cancel');await click('View case SYN-007-001')
 for(const screen of ['Identity Verification','AI Assessment','Supervisor Review','Action & Closure','Audit History']){await nav(screen);await inspect()}
 await nav('Identity Verification');await verify();await nav('AI Assessment');await click('Run AI Assessment');await inspect();assert.equal(await page.locator('.report-section').count(),9);assert.ok((await page.locator('.case-report').innerText()).includes('Natalie Mercer'));assert.ok((await page.locator('.case-report').innerText()).includes('AI ASSESSMENT'))
 await page.screenshot({path:`${artifactDir}/professional-assessment.png`,fullPage:true});await check('I have reviewed');await click('Record human AI review');await click('Request Supervisor review');await approve();await inspect();await nav('Action & Closure');assert.equal(await page.locator('.workflow-panel select').count(),0);await click('Process Reversal');await inspect();assert.ok((await page.locator('.workflow-panel').innerText()).includes('Training result · No live transaction processed.'));await nav('Audit History');await inspect();await page.screenshot({path:`${artifactDir}/professional-audit.png`,fullPage:true})
})
await test('Read-only assigned methods, verification outcomes and incomplete JSON export',async()=>{
  for(const [i,method] of ['Security questions','One-time verification code','Identity document review'].entries()){
    await page.goto('http://localhost:5173');await click(`View case SYN-007-00${i+1}`)
    assert.ok((await page.locator('.verification-record').innerText()).includes(method))
    assert.ok((await page.locator('.verification-record').innerText()).includes('Not completed'))
    assert.equal(await page.locator('.workflow-panel select').count(),0)
  }
  await start();await verify();assert.ok((await page.locator('.verification-record').innerText()).includes('Completed'))
  await start();await click('Unable to Verify Identity');await page.getByLabel('Incomplete-verification reason').selectOption({index:1});await check('I, the CSR, confirm closure');await click('Confirm incomplete-verification closure')
  assert.ok((await page.locator('.verification-record').innerText()).includes('Incomplete'))
  assert.ok((await page.locator('.verification-record').innerText()).includes('Security questions'))
  await page.screenshot({path:`${artifactDir}/incomplete-verification.png`,fullPage:true})
  await nav('Audit History');const downloadPromise=page.waitForEvent('download');await click('Download JSON audit');const download=await downloadPromise;await download.saveAs(`${artifactDir}/incomplete-audit.json`)
  const data=JSON.parse(await readFile(`${artifactDir}/incomplete-audit.json`,'utf8'));assert.equal(data.cases[0].verification.method,'Security questions');assert.equal(data.cases[0].verification.status,'Incomplete');assert.ok(data.cases[0].events.some(e=>e.type==='verification_incomplete'&&e.details.method==='Security questions'&&e.details.outcome==='Incomplete'))
})
await test('Verification bypasses and unauthorized human actions',async()=>{await start(); await click('Confirm Verification'); await notice('explicitly confirm'); await role('Supervisor'); await check('I, the CSR, confirm that'); await click('Confirm Verification'); await notice('CSR Access Required'); await role('CSR'); await nav('AI Assessment'); for(const name of ['Run AI Assessment','Record human AI review']){await click(name);await notice('verification is mandatory')} await nav('Action & Closure'); await click('Process Reversal'); await notice('Supervisor assistance is needed for this action. No approval or account change has been performed.')})
await test('Evidence editor absent; internal unavailable-evidence fixture retains all gates',async()=>{await start();await assertEvidenceSectionAbsent(page);assert.ok(await page.getByRole('checkbox',{name:'I, the CSR, confirm that'}).isVisible());await page.screenshot({path:`${artifactDir}/verification-screen.png`,fullPage:true});await openMaterialFixture(page);await assertEvidenceSectionAbsent(page);assert.ok(await page.getByText('Evidence unavailable',{exact:true}).isVisible());await verify();await notice('evidence is unavailable');await nav('AI Assessment');await click('Run AI Assessment');await notice('verification is mandatory');await nav('Action & Closure');await click('Process Reversal');await notice('Supervisor assistance is needed')})
await test('Normal AI simulation has no outcome controls, preserves structured report and human review gate',async()=>{
 await start();await verify();await nav('AI Assessment');assert.equal(await page.locator('.workflow-panel select').count(),0);assert.equal(await page.getByRole('button',{name:'Complete Assessment Without AI',exact:true}).count(),0)
 await click('Request Supervisor review');await notice('human-reviewed assessment');await click('Run AI Assessment');assert.ok(await page.getByRole('heading',{name:'AI Assessment Complete',exact:true}).isVisible());await notice('Assessment ready for CSR review.');assert.equal(await page.getByText('Training assessment · No live transaction processed.',{exact:true}).count(),0);assert.equal(await page.locator('.report-section').count(),9);assert.equal(await page.getByRole('button',{name:'Complete Assessment Without AI',exact:true}).count(),0);await click('Record human AI review');await notice('Explicit human review');await click('Request Supervisor review');await notice('human-reviewed assessment');await page.screenshot({path:`${artifactDir}/assessment-screen.png`,fullPage:true});await check('I have reviewed');await click('Record human AI review');await notice('Human assessment recorded')
})
await test('Uncertainty fixture requires explicit acknowledgment',async()=>{await withAIOutcome(page,'uncertain',async()=>{await start();await verify();await nav('AI Assessment');await click('Run AI Assessment');assert.ok(await page.getByRole('alert').isVisible());assert.equal(await page.getByRole('button',{name:'Complete Assessment Without AI',exact:true}).count(),0);await check('I have reviewed');await click('Record human AI review');await notice('Acknowledge the uncertainty');await check('I acknowledge the uncertain');await click('Record human AI review');await notice('Human assessment recorded')})})
await test('Failed, unusable and unavailable fixtures expose guarded assessment without AI',async()=>{
 for(const mode of ['unusable','failed','unavailable'])await withAIOutcome(page,mode,async()=>{await start();await verify();await nav('AI Assessment');await click('Run AI Assessment');await notice('Complete Assessment Without AI');assert.equal(await page.getByRole('heading',{name:'AI Assessment Complete',exact:true}).count(),0);await click('Complete Assessment Without AI');await notice('Explicit human review');await check('I have reviewed');await click('Record human AI review');await notice('Complete Assessment Without AI');await role('Supervisor');await click('Complete Assessment Without AI');await notice('CSR Access Required');await role('CSR');await click('Complete Assessment Without AI');await notice('Human assessment recorded');await nav('Audit History');assert.ok((await page.locator('.audit-list').innerText()).includes(mode))})
})
await test('Supervisor approval is separate; role and explicit decision guards',async()=>{await start();await verify();await assess();await nav('Supervisor Review');assert.ok(await page.getByText('Supervisor Access Required',{exact:true}).isVisible());assert.ok(await page.getByText('Supervisor Approval Required',{exact:true}).isVisible());assert.ok(await page.getByText('This $500 transaction reversal requires Supervisor approval before processing. Submitting a request for review does not authorize the reversal.',{exact:true}).isVisible());assert.ok(await page.getByText('Only a Supervisor can review and approve this request.',{exact:true}).isVisible());assert.ok((await page.locator('.review-details').innerText()).includes('Supervisor Approval: Pending'));for(const name of ['Approve Reversal','Reject request'])assert.ok(await page.getByRole('button',{name,exact:true}).isDisabled());assert.ok(await page.getByRole('checkbox',{name:'I, the human Supervisor'}).isDisabled());await page.screenshot({path:`${artifactDir}/supervisor-access-required.png`,fullPage:true});await role('Supervisor');assert.equal(await page.getByText('Supervisor Access Required',{exact:true}).count(),0);assert.ok(await page.getByRole('button',{name:'Approve Reversal',exact:true}).isEnabled());await page.getByRole('checkbox',{name:'I, the human Supervisor'}).uncheck();await click('Approve Reversal');await notice('explicitly confirm');await check('I, the human Supervisor');await click('Approve Reversal');await notice('separate CSR-triggered');await nav('Action & Closure');await click('Process Reversal');await notice('CSR Access Required');await click('Confirm Case Closure');await notice('CSR Access Required')})
await test('Failed mock reversal stays open; duplicate and closure controls disabled',async()=>{await withReversalOutcome(page,'failed',async()=>{await prepare();await click('Process Reversal');await notice('failed. Case remains open');assert.ok(await page.getByRole('button',{name:'Process Reversal',exact:true}).isDisabled());assert.ok(await page.getByRole('button',{name:'Confirm Case Closure',exact:true}).isDisabled())})})
await test('Rejected cases stay open until eligible CSR cancellation',async()=>{await start();await verify();await assess();await nav('Supervisor Review');await role('Supervisor');await check('I, the human Supervisor');await click('Reject request');await notice('Case remains open for review');await nav('Action & Closure');assert.ok(await page.getByRole('button',{name:'Confirm Case Closure',exact:true}).isDisabled());await role('CSR');await click('Close / Cancel Case');await page.getByLabel('Cancellation reason').selectOption({index:1});await check('I, the CSR, explicitly confirm cancellation');await click('Confirm Cancellation');await notice('Closed — Cancelled')})
await test('CSR cancellation requires verification, reason and confirmation; closed status and JSON block further actions',async()=>{
 await start();await nav('Action & Closure');await click('Close / Cancel Case');await page.getByLabel('Cancellation reason').selectOption({index:1});await check('I, the CSR, explicitly confirm cancellation');await click('Confirm Cancellation');await notice('Current CSR verification is required');await nav('Identity Verification');await verify();await nav('Action & Closure');await click('Close / Cancel Case');await click('Confirm Cancellation');await notice('Select a cancellation reason');await page.getByLabel('Cancellation reason').selectOption({index:1});await click('Confirm Cancellation');await notice('Explicit human CSR confirmation');await check('I, the CSR, explicitly confirm cancellation');await click('Keep Case Open');assert.equal(await page.getByRole('button',{name:'Confirm Cancellation',exact:true}).count(),0);await click('Close / Cancel Case');await page.getByLabel('Cancellation reason').selectOption({index:1});await check('I, the CSR, explicitly confirm cancellation');await role('Supervisor');assert.ok(await page.getByRole('button',{name:'Confirm Cancellation',exact:true}).isDisabled());await role('CSR');await click('Confirm Cancellation');await notice('Closed — Cancelled');assert.ok(await page.getByRole('button',{name:'Close / Cancel Case',exact:true}).isDisabled());await page.screenshot({path:`${artifactDir}/cancelled-case.png`,fullPage:true})
 await nav('AI Assessment');assert.ok(await page.getByRole('button',{name:'Run AI Assessment',exact:true}).isDisabled());await nav('Supervisor Review');assert.ok(await page.getByRole('button',{name:'Approve Reversal',exact:true}).isDisabled());await nav('Action & Closure');assert.ok(await page.getByRole('button',{name:'Process Reversal',exact:true}).isDisabled());assert.ok(await page.getByRole('button',{name:'Confirm Case Closure',exact:true}).isDisabled());await nav('Audit History');const before=await page.locator('.audit-list').innerText();const pending=page.waitForEvent('download');await click('Download JSON audit');await (await pending).saveAs(`${artifactDir}/cancelled-audit.json`);const data=JSON.parse(await readFile(`${artifactDir}/cancelled-audit.json`,'utf8'));const item=data.cases[0];assert.equal(item.status,'Closed — Cancelled');assert.equal(item.closureOutcome,'cancelled');assert.equal(item.cancellationReason,'Customer no longer wishes to proceed');for(const type of ['human_decision','human_closure_confirmation','case_transition']){const event=item.events.find(e=>e.type===type&&e.details.reason===item.cancellationReason);assert.ok(event);assert.equal(event.actor,'CSR');assert.ok(Number.isFinite(Date.parse(event.timestamp)))}assert.equal(await page.locator('.audit-list').innerText(),before)
})
await test('Processed successful and failed reversals cannot cancel; no automatic corrective action',async()=>{
 for(const outcome of ['success','failed'])await withReversalOutcome(page,outcome,async()=>{await prepare();await click('Process Reversal');await click('Close / Cancel Case');await notice('Supervisor review is required');assert.ok((await page.locator('.workflow-panel').innerText()).includes('No reversal has been undone.'));assert.equal(await page.getByRole('button',{name:'Confirm Cancellation',exact:true}).count(),0)})
})
await test('Complete $500 success, separate human closure, audit JSON and export immutability',async()=>{await start();await verify();await nav('AI Assessment');await click('Run AI Assessment');await check('I have reviewed');await click('Record human AI review');await click('Request Supervisor review');await approve();await nav('Action & Closure');await click('Confirm Case Closure');await notice('successfully resolved');await click('Process Reversal');await notice('Case is still open');assert.ok(await page.getByRole('button',{name:'Process Reversal',exact:true}).isDisabled());await click('Confirm Case Closure');await notice('Explicit human CSR confirmation');await check('I, the human CSR, explicitly');await click('Confirm Case Closure');await notice('confirmed case closure');await nav('Audit History');const before=await page.locator('.audit-list').innerText();const downloadPromise=page.waitForEvent('download');await click('Download JSON audit');const download=await downloadPromise;await download.saveAs(`${artifactDir}/success-audit.json`);const data=JSON.parse(await readFile(`${artifactDir}/success-audit.json`,'utf8'));assert.equal(data.simulationOnly,true);assert.equal(data.cases.length,3);assert.equal(data.cases[0].status,'Closed — Successfully Resolved');assert.equal(data.cases[0].verification.status,'Completed');assert.equal(data.cases[0].verification.method,'Security questions');for(const t of ['verification_attestation','simulated_ai_output','human_assessment','supervisor_approval','csr_mock_reversal_triggered','simulated_action_result','human_closure_confirmation','case_transition'])assert.ok(data.cases[0].events.some(e=>e.type===t));assert.equal(await page.locator('.audit-list').innerText(),before);await page.screenshot({path:`${artifactDir}/success-audit.png`,fullPage:true})})
await test('Routine CSR requests complete and close without Supervisor approval or financial controls',async()=>{
 for(const id of ['SYN-007-002','SYN-007-003']){
  await page.goto('http://localhost:5173');await click(`View case ${id}`);await nav('Action & Closure');await click('Complete Request');await notice('verification is mandatory');await nav('Identity Verification');await verify();await nav('AI Assessment');assert.equal(await page.getByRole('button',{name:'Request Supervisor review',exact:true}).count(),0);await click('Run AI Assessment');assert.ok((await page.locator('.case-report').innerText()).includes('Supervisor Approval: Not Required'));await check('I have reviewed');await click('Record human AI review');await click('Next Step → Action & Closure');assert.equal(await page.getByRole('button',{name:'Process Reversal',exact:true}).count(),0);await click('Confirm Case Closure');await notice('CSR-completed request');await click('Complete Request');await notice('Explicit human CSR confirmation');await check('I, the CSR, confirm that I have completed');await role('Supervisor');await click('Complete Request');await notice('CSR Access Required');await role('CSR');await click('Complete Request');await notice('remains open');await page.screenshot({path:`${artifactDir}/routine-completion-${id}.png`,fullPage:true});await click('Confirm Case Closure');await notice('Explicit human CSR confirmation');await check('I, the human CSR, explicitly');await click('Confirm Case Closure');await notice('confirmed case closure');await nav('Supervisor Review');assert.equal(await page.getByRole('button',{name:'Approve Reversal',exact:true}).count(),0);await nav('Audit History');const pending=page.waitForEvent('download');await click('Download JSON audit');const filename=`${artifactDir}/routine-${id}-audit.json`;await (await pending).saveAs(filename);const data=JSON.parse(await readFile(filename,'utf8'));const item=data.cases.find(c=>c.caseId===id);assert.equal(item.status,'Closed — Successfully Resolved');assert.equal(item.routing.route,'csr');assert.equal(item.routing.approvalRequired,false);assert.equal(item.routing.policyVersion,'AMX-routing-1');assert.ok(item.events.some(e=>e.type==='csr_request_completed'));assert.ok(!item.events.some(e=>['supervisor_approval','csr_mock_reversal_triggered'].includes(e.type)));assert.ok(item.events.every(e=>e.routing.caseRevision===e.revision));await page.screenshot({path:`${artifactDir}/routine-${id}.png`,fullPage:true})
 }
})
await test('Exceptions and unsupported requests remain on hold for human review without processing authority',async()=>{
 for(const exception of ['evidenceConflict','requiresAccountChange','unsupported']){await openRoutingFixture(page,exception);await verify();await nav('AI Assessment');await click('Run AI Assessment');await check('I have reviewed');await click('Record human AI review');await click('Request Supervisor review');await click('Next Step → Supervisor Review');assert.equal(await page.getByRole('button',{name:'Approve Reversal',exact:true}).count(),0);assert.ok((await page.locator('.workflow-panel').innerText()).includes('No completion, financial approval, or processing path is authorized'));await nav('Action & Closure');assert.equal(await page.getByRole('button',{name:'Process Reversal',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Complete Request',exact:true}).count(),0);await click('Confirm Case Closure');await notice('No financial processing or approval is authorized')}
})
await test('Browser refresh resets all cases and audit',async()=>{await page.reload();await page.getByRole('button',{name:'View case SYN-007-001'}).waitFor();assert.equal(await page.getByText('Open · Unverified',{exact:true}).count(),3);await click('View case SYN-007-001');await nav('Audit History');assert.ok(await page.getByText('No workflow events recorded for this case.').isVisible());assert.deepEqual(errors,[])})
} finally {await writeFile(`${artifactDir}/browser-results.json`,JSON.stringify({browser:browser.version(),results,pageErrors:errors},null,2));await browser.close()}
if(results.some(r=>r.result==='FAIL'))process.exitCode=1
