import test from 'node:test'
import assert from 'node:assert/strict'
import { createCase, caseStore, nextSyntheticId, transactionReference, syntheticCustomers, descriptions } from '../src/caseCreation.js'
import { createCases, transition, supervisorMessage } from '../src/workflow.js'
const input = () => ({ customer: syntheticCustomers[0], requestType: 'Reversal request', amount: '500.00', description: descriptions['Reversal request'][0] })
const create = () => { const result = createCase(createCases(), 'CSR', input()); assert.equal(result.blocked, false); return result.item }
const allowed = (item, action, payload, role = 'CSR') => { const result = transition(item, role, action, payload); assert.equal(result.blocked, false, result.message); return result.item }
const blocked = (item, action, payload, role = 'CSR', message) => { const result = transition(item, role, action, payload); assert.equal(result.blocked, true); const {audit: oldAudit, ...oldState} = item; const {audit, ...newState} = result.item; assert.deepEqual(newState, oldState); assert.equal(audit.length, oldAudit.length + 1); assert.equal(audit.at(-1).type, 'blocked_action'); if (message) assert.equal(result.message,message) }
const verified = () => allowed(create(), 'verify', {attested:true})
const escalated = () => allowed(allowed(verified(), 'assess', {method:'manual',reviewed:true}), 'escalate')
const approved = () => allowed(escalated(), 'approve', {confirmed:true}, 'Supervisor')

test('creation initializes every authority gate and audits synthetic fields', () => { const cases = createCases(); const before = JSON.stringify(cases); const result = createCase(cases, 'CSR', input(), '2026-10-09T20:00:00Z'); const s = result.item; assert.equal(JSON.stringify(cases),before); assert.equal(s.id,'SYN-007-004'); assert.equal(s.transactionReference,'SYN-TXN-007-004'); assert.equal(s.status,'open'); assert.equal(s.verified,false); assert.equal(s.evidence,true); assert.equal(s.revision,1); assert.equal(s.disposition,'active'); assert.equal(s.escalated,false); for(const k of ['assessment','ai','approval','actionResult'])assert.equal(s[k],null); assert.equal(s.audit.length,1); assert.equal(s.audit[0].type,'case_created'); assert.equal(s.audit[0].caseId,s.id); assert.equal(s.audit[0].actor,'CSR'); assert.equal(s.audit[0].details.simulationOnly,true); assert.equal(s.audit[0].timestamp,'2026-10-09T20:00:00Z') })
for(const role of ['Supervisor','AI','Admin','']) test(`creation denied for ${role || 'missing'} role`, () => {const result=createCase(createCases(),role,input());assert.equal(result.blocked,true);assert.equal(result.item,undefined)})
for(const [name, patch] of [ ['unknown name',{customer:'Unapproved example'}], ['unknown type',{requestType:'Account change'}], ['free description',{description:'Unapproved text'}], ['non-$500 reversal',{amount:'100.00'}], ['negative amount',{amount:'-500.00'}], ['number amount',{amount:500}], ['nonfinite amount',{amount:'Infinity'}], ['caller ID',{id:'SYN-007-001'}], ['caller reference',{transactionReference:'external'}], ['injected verification',{verified:true}], ['injected approval',{approval:{revision:1}}] ]) test(`reject ${name} without creating or mutating a case`,()=>{const cases=createCases();const before=JSON.stringify(cases);const result=createCase(cases,'CSR',{...input(),...patch});assert.equal(result.blocked,true);assert.equal(result.item,undefined);assert.equal(JSON.stringify(cases),before)})
test('empty and null payloads rejected',()=>{for(const value of [{},null])assert.equal(createCase(createCases(),'CSR',value).blocked,true)})
test('IDs skip collisions; generated references are unique for repeated submissions',()=>{let cases=createCases();for(let i=0;i<30;i++){const s=createCase(cases,'CSR',input()).item;cases=[...cases,s]}assert.equal(new Set(cases.map(s=>s.id)).size,33);assert.equal(new Set(cases.slice(3).map(s=>s.transactionReference)).size,30);assert.equal(nextSyntheticId([...createCases(),{id:'SYN-007-004'},{id:'SYN-007-006'}]),'SYN-007-005');assert.equal(transactionReference('SYN-007-005'),'SYN-TXN-007-005')})
test('reducer serializes queued submissions and clears form after success',()=>{let state={cases:createCases(),creating:true,notice:null};const action={type:'create',role:'CSR',input:input(),caseId:state.cases[0].id,timestamp:'2026-10-09T20:00:00Z'};state=caseStore(state,action);state=caseStore(state,action);assert.deepEqual(state.cases.slice(3).map(s=>s.id),['SYN-007-004','SYN-007-005']);assert.equal(state.creating,false)})
test('blocked creation logs reason only, retains form, adds no case',()=>{const initial={cases:createCases(),creating:true,notice:null};for(const [role,payload] of [['Supervisor',input()],['CSR',{...input(),customer:'Rejected arbitrary input'}]]){const state=caseStore(initial,{type:'create',role,input:payload,caseId:initial.cases[0].id,timestamp:'2026-10-09T20:00:00Z'});assert.equal(state.cases.length,3);assert.equal(state.creating,true);assert.equal(state.notice.blocked,true);assert.equal(state.cases[0].audit.at(-1).details.action,'create_case');assert.ok(!JSON.stringify(state.cases).includes('Rejected arbitrary input'))}})
for(const type of ['Statement explanation request','Transaction inquiry']) test(`${type} uses existing information-case safeguards`,()=>{let s=createCase(createCases(),'CSR',{...input(),requestType:type,amount:'25.00',description:descriptions[type][0]}).item;assert.equal(s.category,'Information request');assert.equal(s.amount,'$25.00');blocked(s,'ai',{mode:'usable'});s=allowed(s,'verify',{attested:true});s=allowed(s,'assess',{method:'manual',reviewed:true});blocked(s,'escalate');blocked(s,'close',{confirmed:true});assert.equal(s.status,'open')})
test('new case verification gate blocks AI, both assessment methods and closure',()=>{const s=create();blocked(s,'ai',{mode:'usable'});for(const method of ['ai','manual'])blocked(s,'assess',{method,reviewed:true});blocked(s,'close',{confirmed:true});blocked(s,'verify',{attested:true},'Supervisor');blocked(s,'verify',{attested:false})})
test('new case missing evidence invalidates authority and blocks verification',()=>{const s=allowed(approved(),'material',{evidence:false,note:'Original synthetic request'});assert.equal(s.approval,null);assert.equal(s.verified,false);blocked(s,'verify',{attested:true});blocked(s,'ai',{mode:'usable'})})
for(const mode of ['usable','uncertain','unusable','failed'])test(`new case AI ${mode} retains gates`,()=>{let s=allowed(verified(),'ai',{mode});assert.equal(s.approval,null);assert.equal(s.status,'open');if(mode==='uncertain')blocked(s,'assess',{method:'ai',reviewed:true});if(['failed','unusable'].includes(mode))blocked(s,'assess',{method:'ai',reviewed:true});s=allowed(s,'assess',{method:['failed','unusable'].includes(mode)?'manual':'ai',reviewed:true,uncertaintyAcknowledged:true});blocked(s,'reverse',{outcome:'success'},'CSR',supervisorMessage)})
test('new case stale approval, unauthorized approval and execution blocked',()=>{blocked(escalated(),'approve',{confirmed:true});const s=approved();blocked(s,'reverse',{outcome:'success'},'Supervisor');blocked({...s,approval:{...s.approval,revision:0}},'reverse',{outcome:'success'},'CSR',supervisorMessage);const changed=allowed(s,'material',{evidence:true,note:'Fictional duplicate-charge context added'});assert.equal(changed.approval,null);blocked(changed,'reverse',{outcome:'success'},'CSR',supervisorMessage)})
for(const outcome of ['rejected','withdrawn','failed-action'])test(`new case ${outcome} remains unresolved`,()=>{const s=outcome==='failed-action'?allowed(approved(),'reverse',{outcome:'failed'}):allowed(escalated(),outcome==='rejected'?'reject':'withdraw',{confirmed:true},outcome==='rejected'?'Supervisor':'CSR');assert.equal(s.status,'open');assert.equal(s.disposition,outcome);blocked(s,'close',{confirmed:true});blocked(s,'reverse',{outcome:'success'})})
test('new $500 case needs separate approval action and explicit human closure',()=>{let s=approved();assert.equal(s.actionResult,null);blocked(s,'close',{confirmed:true});s=allowed(s,'reverse',{outcome:'success'});assert.equal(s.status,'open');blocked(s,'reverse',{outcome:'success'});blocked(s,'close',{confirmed:true},'Supervisor');blocked(s,'close',{confirmed:false});s=allowed(s,'close',{confirmed:true});assert.equal(s.status,'closed');assert.equal(s.approval.amount,'$500.00');assert.equal(s.audit[0].type,'case_created');assert.equal(new Set(s.audit.map(e=>e.id)).size,s.audit.length);assert.ok(s.audit.every(e=>e.caseId===s.id));assert.deepEqual(JSON.parse(JSON.stringify(s.audit)),s.audit)})
test('created cases do not alter refresh initialization',()=>{create();assert.equal(createCases().length,3);assert.ok(createCases().every(s=>s.audit.length===0&&!s.verified&&s.status==='open'))})
