import test from 'node:test'
import assert from 'node:assert/strict'
import { createCases, transition, caseStatus } from '../src/workflow.js'
import { createCase, syntheticCustomers, descriptions } from '../src/caseCreation.js'
import { verificationMethods, incompleteReasons, hasValidVerification, verificationStatus, canAssess, assessmentNextStep } from '../src/verification.js'
import { draftCustomerCommunication } from '../src/caseReport.js'
const fresh = () => createCases()[0]
const ok = (s, a, p = {}, role = 'CSR') => { const result = transition(s,role,a,p); assert.equal(result.blocked,false,result.message); return result.item }
const blocked = (s,a,p={},role='CSR') => { const result=transition(s,role,a,p);assert.equal(result.blocked,true,result.message);const {audit: oldAudit,...before}=s;const {audit,...after}=result.item;assert.deepEqual(after,before);assert.equal(audit.length,oldAudit.length+1);assert.equal(audit.at(-1).type,'blocked_action');return result }
const verified = (s=fresh(),method=s.verificationMethod) => ok(s,'verify',{attested:true,method})
const withReport = (s=verified(),mode='usable') => ok(s,'ai',{mode})
const assessed = (s=withReport()) => ok(s,'assess',{method:'ai',reviewed:true,uncertaintyAcknowledged:true})
const escalated = (s=assessed()) => ok(s,'escalate')
const approved = (s=escalated()) => ok(s,'approve',{confirmed:true},'Supervisor')
const incompletePayload = {reason:incompleteReasons[1],confirmed:true}

for(const method of verificationMethods)test(`approved method ${method} requires and records human attestation`,()=>{blocked(fresh(),'verify',{method,attested:false});const s=verified({...fresh(),verificationMethod:method},method);assert.equal(hasValidVerification(s),true);assert.equal(s.verificationMethod,method);assert.equal(s.verificationRevision,s.revision);assert.equal(s.audit[0].details.method,method);assert.equal(s.audit[0].details.attestedBy,'Human CSR');assert.equal(canAssess(s,'CSR'),true);blocked(s,'verify',{method,attested:true})})
for(const method of ['','Unapproved method',0])test(`invalid method ${String(method)} denied`,()=>blocked(fresh(),'verify',{method,attested:true}))
test('truthy nonboolean attestation cannot verify',()=>blocked(fresh(),'verify',{method:verificationMethods[0],attested:'yes'}))
test('verification boolean without valid current method cannot bypass processing',()=>{for(const s of [{...fresh(),verified:true,verificationMethod:null},{...verified(),verificationRevision:0},{...verified(),verificationMethod:'Unapproved method'}]){assert.equal(hasValidVerification(s),false);assert.equal(canAssess(s,'CSR'),false);blocked(s,'ai',{mode:'usable'});blocked(s,'assess',{method:'manual',reviewed:true})}})
for(const reason of incompleteReasons)test(`incomplete reason ${reason} closes only by explicit CSR decision`,()=>{const s=ok(fresh(),'close_incomplete',{reason,confirmed:true});assert.equal(s.status,'closed');assert.equal(s.closureOutcome,'incomplete-verification');assert.equal(s.verified,false);assert.equal(s.verificationMethod,fresh().verificationMethod);assert.equal(verificationStatus(s),'Incomplete');assert.equal(caseStatus(s),'Closed — Incomplete Verification');assert.deepEqual(s.audit.map(e=>e.type),['verification_incomplete','human_decision','human_closure_confirmation','case_transition']);assert.equal(s.audit[0].details.reason,reason);assert.equal(s.audit.at(-1).details.outcome,'incomplete-verification');for(const k of ['ai','assessment','approval','actionResult'])assert.equal(s[k],null);assert.equal(s.escalated,false)})
test('incomplete closure works for each active unverified synthetic case type',()=>{for(const s of createCases())assert.equal(ok(s,'close_incomplete',incompletePayload).closureOutcome,'incomplete-verification');const s=createCase(createCases(),'CSR',{customer:syntheticCustomers[0],requestType:'Reversal request',amount:'500.00',description:descriptions['Reversal request'][0]}).item;assert.equal(ok(s,'close_incomplete',incompletePayload).audit[0].type,'case_created')})
for(const role of ['Supervisor','AI','Administrator',''])test(`role ${role || 'missing'} cannot close incomplete`,()=>blocked(fresh(),'close_incomplete',incompletePayload,role))
test('missing/invalid reason and missing/nonboolean confirmation denied',()=>{for(const p of [{confirmed:true},{reason:'Arbitrary text',confirmed:true},{reason:incompleteReasons[0]},{reason:incompleteReasons[0],confirmed:false},{reason:incompleteReasons[0],confirmed:'yes'}])blocked(fresh(),'close_incomplete',p)})
test('incomplete closure bypass is denied after current downstream processing or invalid case status',()=>{for(const s of [verified(),withReport(),assessed(),approved(),ok(approved(),'reverse',{outcome:'success'}),{...fresh(),ai:{}},{...fresh(),assessment:{}},{...fresh(),approval:{}},{...fresh(),escalated:true},{...fresh(),actionResult:'failed'},{...fresh(),status:'invalid'}])blocked(s,'close_incomplete',incompletePayload)})
test('closed-incomplete case blocks duplicate closure and all processing, decision and action attempts',()=>{const s=ok(fresh(),'close_incomplete',incompletePayload);for(const a of ['close_incomplete','verify','ai','assess','escalate','approve','reject','reverse','close','withdraw','material'])blocked(s,a,{...incompletePayload,attested:true,method:verificationMethods[0],mode:'usable',reviewed:true,outcome:'success',evidence:true,note:'Original synthetic request'},['approve','reject'].includes(a)?'Supervisor':'CSR')})
test('missing evidence can close incomplete but cannot verify or process',()=>{const s=ok(fresh(),'material',{evidence:false,note:'Original synthetic request'});blocked(s,'verify',{attested:true,method:verificationMethods[0]});blocked(s,'ai',{mode:'usable'});assert.equal(ok(s,'close_incomplete',{reason:incompleteReasons[0],confirmed:true}).verified,false)})
test('material changes preserve assigned method and reset report and authority; old attestation cannot authorize new revision',()=>{const s=ok(approved(),'material',{evidence:true,note:'Fictional duplicate-charge context added'});assert.equal(s.verificationMethod,fresh().verificationMethod);assert.equal(s.verificationRevision,null);assert.equal(s.verified,false);assert.equal(s.ai,null);assert.equal(s.approval,null);assert.equal(s.assessment,null);assert.equal(s.escalated,false);blocked(s,'ai',{mode:'usable'});assert.equal(ok(s,'close_incomplete',incompletePayload).closureOutcome,'incomplete-verification')})
for(const outcome of ['rejected','failed-action'])test(`${outcome} cannot use incomplete exception and remains open`,()=>{const s=outcome==='failed-action'?ok(approved(),'reverse',{outcome:'failed'}):ok(escalated(),'reject',{confirmed:true},'Supervisor');blocked(s,'close_incomplete',incompletePayload);blocked(s,'close',{confirmed:true});assert.equal(s.status,'open');assert.equal(s.disposition,outcome)})
test('successful closure is distinct and keeps method; incomplete exception cannot close it again',()=>{const s=ok(ok(approved(),'reverse',{outcome:'success'}),'close',{confirmed:true});assert.equal(caseStatus(s),'Closed — Successfully Resolved');assert.equal(s.closureOutcome,'successfully-resolved');assert.equal(s.verificationMethod,verificationMethods[0]);assert.equal(s.ai.report.humanDecisions.closure,'Human CSR closure recorded: successfully-resolved.');blocked(s,'close_incomplete',incompletePayload)})
test('Next Step eligibility checks role, method, revision, evidence and active/open state',()=>{assert.equal(canAssess(fresh(),'CSR'),false);assert.equal(canAssess(verified(),'CSR'),true);for(const [s,role] of [[verified(),'Supervisor'],[{...verified(),evidence:false},'CSR'],[{...verified(),status:'closed'},'CSR'],[{...verified(),disposition:'rejected'},'CSR'],[{...verified(),actionResult:'success'},'CSR'],[{...verified(),verificationRevision:0},'CSR']])assert.equal(canAssess(s,role),false)})
test('assessment navigation requires actual reviewed escalation and then routes according to recorded approval',()=>{assert.equal(assessmentNextStep(withReport(),'CSR'),null);assert.equal(assessmentNextStep(assessed(),'CSR'),null);assert.equal(assessmentNextStep(escalated(),'CSR'),'supervisor');assert.equal(assessmentNextStep(escalated(),'Supervisor'),null);assert.equal(assessmentNextStep(approved(),'CSR'),'action');assert.equal(assessmentNextStep(ok(approved(),'reverse',{outcome:'success'}),'CSR'),null)})
for(const index of [0,1,2])test(`report for case ${index+1} uses selected facts and no invented context`,()=>{const s=withReport(verified(createCases()[index]));const r=s.ai.report;assert.equal(r.caseId,s.id);assert.ok(r.customerRequestSummary.includes(s.customer));assert.ok(r.customerRequestSummary.includes(s.description));assert.equal(r.requestClassification.category,s.category);assert.ok(r.evidenceAndKnownFacts.providedFacts.includes(`Fictional amount: ${s.amount}`));assert.ok(r.missingInformation.some(text=>text.includes('not supplied')));assert.equal(r.verificationStatus.actor,'Human CSR');assert.equal(r.verificationStatus.method,s.verificationMethod);assert.ok(r.evidenceAndKnownFacts.assumptions[0].includes('No additional facts'));for(const other of createCases().filter(item=>item.id!==s.id))assert.ok(!JSON.stringify(r).includes(other.customer));assert.equal(r.draftCustomerCommunication.label,'Draft — Human Review Required');assert.ok(r.recommendedNextSteps[1].includes('do not justify Fraud, Legal, IT, or Operations referral'));assert.deepEqual(s.audit.find(e=>e.type==='simulated_ai_output').details.report,r)})
test('new-case report includes generated reference and chosen description exactly',()=>{let s=createCase(createCases(),'CSR',{customer:syntheticCustomers[2],requestType:'Reversal request',amount:'500.00',description:descriptions['Reversal request'][1]}).item;s=withReport(verified(s));assert.ok(s.ai.report.customerRequestSummary.includes(s.description));assert.ok(s.ai.report.evidenceAndKnownFacts.providedFacts.includes(`Synthetic transaction reference: ${s.transactionReference}`));assert.ok(s.ai.report.evidenceAndKnownFacts.supportedConclusions.every(text=>!text.includes('confirmed duplicate')))})
test('report deterministic for identical inputs and generated only after verification',()=>{const s=verified();assert.deepEqual(withReport(s).ai.report,withReport(s).ai.report);blocked(fresh(),'ai',{mode:'usable'});assert.equal(fresh().ai,null)})
test('uncertain report requires acknowledgment and retains unknowns',()=>{const s=withReport(verified(),'uncertain');assert.ok(s.ai.report.uncertainty.includes('Uncertainty warning'));assert.ok(s.ai.report.missingInformation.some(text=>text.includes('incomplete transaction context')));blocked(s,'assess',{method:'ai',reviewed:true});assert.equal(assessed(s).assessment.uncertaintyAcknowledged,true)})
for(const mode of ['failed','unusable','unavailable'])test(`${mode} AI generates no report and requires guarded manual fallback`,()=>{const s=withReport(verified(),mode);assert.equal(s.ai.report,null);assert.equal(s.ai.summary,null);blocked(s,'assess',{method:'ai',reviewed:true});assert.equal(ok(s,'assess',{method:'manual',reviewed:true}).assessment.method,'manual')})
test('report regeneration revokes prior approval before drafting any authority claims',()=>{const s=withReport(approved());assert.equal(s.approval,null);assert.equal(s.escalated,false);assert.ok(s.ai.report.humanDecisions.approval.startsWith('Supervisor Approval: Pending.'));assert.ok(s.ai.report.draftCustomerCommunication.text.includes('no approval, reversal, or closure'));assert.equal(s.ai.report.humanDecisions.escalation,'No escalation recorded.')})
test('human status refreshes draft accurately without mutating original AI audit snapshot',()=>{let s=withReport();const snapshot=JSON.stringify(s.audit.find(e=>e.type==='simulated_ai_output').details);assert.ok(s.ai.report.draftCustomerCommunication.text.includes('awaits human assessment'));s=assessed(s);assert.ok(s.ai.report.draftCustomerCommunication.text.includes('recorded an assessment'));s=escalated(s);assert.ok(s.ai.report.draftCustomerCommunication.text.includes('requested Supervisor review'));s=approved(s);assert.ok(s.ai.report.draftCustomerCommunication.text.includes('still required'));assert.ok(s.ai.report.draftCustomerCommunication.text.includes('no reversal has been performed'));s=ok(s,'reverse',{outcome:'success'});assert.ok(s.ai.report.draftCustomerCommunication.text.includes('case remains open'));s=ok(s,'close',{confirmed:true});assert.ok(s.ai.report.draftCustomerCommunication.text.includes('confirmed simulated closure'));assert.equal(JSON.stringify(s.audit.find(e=>e.type==='simulated_ai_output').details),snapshot);assert.equal(s.audit.filter(e=>e.type==='simulated_ai_output').length,1);assert.ok(s.audit.some(e=>e.type==='report_human_status_updated'&&e.details.source.includes('no new AI processing')));assert.deepEqual(JSON.parse(JSON.stringify(s.audit)),s.audit)})
test('drafts distinguish rejection cancellation failure and incomplete closure without claiming resolution',()=>{const rejected=ok(escalated(),'reject',{confirmed:true},'Supervisor');const cancelled=ok(escalated(),'cancel',{reason:'Customer no longer wishes to proceed',confirmed:true});const failed=ok(approved(),'reverse',{outcome:'failed'});const incomplete=ok(fresh(),'close_incomplete',incompletePayload);assert.ok(draftCustomerCommunication(rejected).includes('rejected'));assert.ok(draftCustomerCommunication(cancelled).includes('cancelled and closed'));assert.ok(draftCustomerCommunication(failed).includes('attempt failed'));assert.ok(draftCustomerCommunication(incomplete).includes('does not authorize any account change'));for(const s of [rejected,failed])assert.ok(draftCustomerCommunication(s).includes('remains open'))})

test('each seeded case has a predefined method before attestation; all outcomes retain it',()=>{
  assert.deepEqual(createCases().map(s=>s.verificationMethod),verificationMethods)
  for(const s of createCases()){
    assert.equal(verificationStatus(s),'Not completed')
    blocked(s,'verify',{attested:true,method:verificationMethods.find(m=>m!==s.verificationMethod)})
    const completed=ok(s,'verify',{attested:true,securityAnswer:'DO_NOT_STORE',code:'DO_NOT_STORE',document:'DO_NOT_STORE'})
    assert.equal(verificationStatus(completed),'Completed')
    assert.equal(completed.audit.at(-1).details.method,s.verificationMethod)
    assert.equal(completed.audit.at(-1).details.outcome,'Completed')
    const incomplete=ok(s,'close_incomplete',incompletePayload)
    assert.equal(incomplete.verificationMethod,s.verificationMethod)
    assert.equal(incomplete.audit[0].details.method,s.verificationMethod)
    assert.equal(incomplete.audit[0].details.outcome,'Incomplete')
    assert.ok(!JSON.stringify(completed).includes('DO_NOT_STORE'))
  }
})
test('new cases automatically cycle fictional methods and audit the initial outcome',()=>{
  let queue=createCases()
  for(let i=0;i<6;i++){
    const s=createCase(queue,'CSR',{customer:syntheticCustomers[0],requestType:'Reversal request',amount:'500.00',description:descriptions['Reversal request'][0]}).item
    assert.equal(s.verificationMethod,verificationMethods[i%3])
    assert.equal(verificationStatus(s),'Not completed')
    assert.equal(s.audit[0].details.verificationMethod,s.verificationMethod)
    assert.equal(s.audit[0].details.verificationOutcome,'Not completed')
    queue=[...queue,s]
  }
})
