import test from 'node:test'
import assert from 'node:assert/strict'
import { createCases, transition, supervisorMessage } from '../src/workflow.js'
const fresh = () => createCases()[0]
const run = (s, a, p = {}, r = 'CSR') => transition(s, r, a, p, '2026-10-09T19:00:00.000Z')
const ok = (s, a, p, r) => { const result = run(s,a,p,r); assert.equal(result.blocked,false,result.message); return result.item }
const blocked = (s,a,p,r,message) => { const result=run(s,a,p,r); assert.equal(result.blocked,true); const {audit: before,...state}=s; const {audit: after,...next}=result.item; assert.deepEqual(next,state); assert.equal(after.length,before.length+1); assert.equal(after.at(-1).type,'blocked_action'); if(message) assert.equal(result.message,message); return result.item }
const verified = () => ok(fresh(),'verify',{attested:true})
const assessed = () => ok(verified(),'assess',{method:'manual',reviewed:true})
const escalated = () => ok(assessed(),'escalate')
const approved = () => ok(escalated(),'approve',{confirmed:true},'Supervisor')
for(const action of ['ai','assess','escalate','approve','reject','close']) test(`unverified ${action} blocked`,()=>blocked(fresh(),action,{mode:'usable',method:'manual',reviewed:true,confirmed:true},['approve','reject'].includes(action)?'Supervisor':'CSR'))
for(const role of ['Supervisor','AI','Administrator','']) test(`${role || 'empty'} cannot attest`,()=>blocked(fresh(),'verify',{attested:true},role))
for(const action of ['ai','assess','material','escalate','reverse','close','withdraw']) test(`Supervisor cannot ${action}`,()=>blocked(approved(),action,{mode:'usable',method:'manual',reviewed:true,confirmed:true,outcome:'success',evidence:true,note:'Original synthetic request'},'Supervisor'))
for(const action of ['approve','reject']) test(`CSR cannot ${action}`,()=>blocked(escalated(),action,{confirmed:true}))
test('explicit attestation required and duplicate blocked',()=>{blocked(fresh(),'verify',{attested:false}); blocked(verified(),'verify',{attested:true})})
test('missing evidence invalidates authority and blocks all processing',()=>{const s=ok(approved(),'material',{evidence:false,note:'Original synthetic request'}); assert.equal(s.verified,false); assert.equal(s.approval,null); blocked(s,'verify',{attested:true}); blocked(s,'ai',{mode:'usable'}); blocked(s,'assess',{method:'manual',reviewed:true})})
test('changed/conflicting context requires fresh verification and approval',()=>{const s=ok(approved(),'material',{evidence:true,note:'Fictional duplicate-charge context added'}); assert.equal(s.revision,2); assert.equal(s.approval,null); assert.equal(s.assessment,null); assert.equal(s.escalated,false); blocked(s,'reverse',{outcome:'success'},'CSR',supervisorMessage); assert.ok(s.audit.some(e=>e.type==='prior_authority_invalidated'))})
for(const mode of ['usable','uncertain','unusable','failed']) test(`AI ${mode} deterministic, advisory, reviewed or manual fallback`,()=>{const s=verified(); const a=ok(s,'ai',{mode}); assert.deepEqual(a.ai,ok(s,'ai',{mode}).ai); assert.equal(a.ai.label,'Simulated AI'); assert.equal(a.approval,null); assert.equal(a.actionResult,null); assert.equal(a.status,'open'); if(['failed','unusable'].includes(mode)){blocked(a,'assess',{method:'ai',reviewed:true}); assert.equal(ok(a,'assess',{method:'manual',reviewed:true}).assessment.method,'manual')}else{if(mode==='uncertain') blocked(a,'assess',{method:'ai',reviewed:true}); assert.equal(ok(a,'assess',{method:'ai',reviewed:true,uncertaintyAcknowledged:true}).assessment.method,'ai')} })
test('AI cannot perform privileged transitions',()=>{for(const a of ['approve','reverse','close']) blocked(approved(),a,{confirmed:true,outcome:'success'},'AI')})
test('invalid modes and absent human review blocked',()=>{blocked(verified(),'ai',{mode:'invalid'}); blocked(verified(),'assess',{method:'manual',reviewed:false}); blocked(verified(),'assess',{method:'ai',reviewed:true})})
test('approval needs escalation and explicit human decision',()=>{blocked(assessed(),'approve',{confirmed:true},'Supervisor'); blocked(escalated(),'approve',{confirmed:false},'Supervisor'); const s=approved(); assert.equal(s.actionResult,null); assert.equal(s.status,'open'); blocked(s,'approve',{confirmed:true},'Supervisor')})
for(const action of ['ai','assess']) test(`${action} invalidates prior approval`,()=>{const s=ok(approved(),action,action==='ai'?{mode:'usable'}:{method:'manual',reviewed:true}); assert.equal(s.approval,null); assert.equal(s.escalated,false); blocked(s,'reverse',{outcome:'success'},'CSR',supervisorMessage)})
test('stale approval and stale assessment blocked at execution',()=>{const s=approved(); blocked({...s,approval:{...s.approval,revision:0}},'reverse',{outcome:'success'},'CSR',supervisorMessage); blocked({...s,assessment:{...s.assessment,revision:0}},'reverse',{outcome:'success'})})
for(const s of [fresh,verified,assessed,escalated]) test(`reversal without authorization (${s.name}) uses exact message`,()=>blocked(s(),'reverse',{outcome:'success'},'CSR',supervisorMessage))
test('failed reversal stays open, cannot retry or close',()=>{const s=ok(approved(),'reverse',{outcome:'failed'}); assert.equal(s.status,'open'); assert.equal(s.disposition,'failed-action'); blocked(s,'reverse',{outcome:'success'}); blocked(s,'close',{confirmed:true})})
for(const action of ['reject','withdraw']) test(`${action} remains unresolved`,()=>{const s=ok(escalated(),action,{confirmed:true},action==='reject'?'Supervisor':'CSR'); assert.equal(s.status,'open'); assert.equal(s.actionResult,null); blocked(s,'close',{confirmed:true}); blocked(s,'reverse',{outcome:'success'})})
test('successful $500 path separates recommendation approval action and human closure',()=>{let s=verified(); s=ok(s,'ai',{mode:'usable'}); s=ok(s,'assess',{method:'ai',reviewed:true}); s=ok(s,'escalate'); s=ok(s,'approve',{confirmed:true},'Supervisor'); blocked(s,'close',{confirmed:true}); s=ok(s,'reverse',{outcome:'success'}); assert.equal(s.status,'open'); blocked(s,'reverse',{outcome:'success'}); blocked(s,'material',{evidence:false,note:'Original synthetic request'}); blocked(s,'close',{confirmed:false}); s=ok(s,'close',{confirmed:true}); assert.equal(s.status,'closed'); blocked(s,'close',{confirmed:true}); const types=s.audit.map(e=>e.type); for(const t of ['verification_attestation','simulated_ai_output','human_assessment','supervisor_review_requested','supervisor_approval','csr_mock_reversal_triggered','simulated_action_result','human_closure_confirmation','case_transition']) assert.ok(types.includes(t)); assert.equal(s.approval.amount,'$500.00'); assert.equal(new Set(s.audit.map(e=>e.id)).size,s.audit.length); for(const e of s.audit) assert.equal(e.caseId,s.id); assert.deepEqual(JSON.parse(JSON.stringify(s.audit)),s.audit)})
for(const index of [1,2]) test(`information case ${index} has no reversal or closure path`,()=>{let s=ok(createCases()[index],'verify',{attested:true}); s=ok(s,'assess',{method:'manual',reviewed:true}); blocked(s,'escalate'); blocked(s,'close',{confirmed:true}); assert.equal(s.status,'open')})
test('fresh session resets all cases and audit',()=>{approved(); for(const s of createCases()){assert.equal(s.verified,false); assert.equal(s.status,'open'); assert.deepEqual(s.audit,[])}})
